package io.github.refux.slangwasm.versiontool;

import io.github.refux.slangwasm.SlangCompiler;
import io.github.refux.slangwasm.SlangRuntime;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Build-time generator for {@code slang-version.properties}: loads the bundled Slang compiler once,
 * reads its build tag via {@link SlangCompiler#version()}, and writes it as a resource that
 * {@code SlangVersion} exposes as {@code BUILD_TAG}. Run by the {@code generateSlangVersion} Gradle
 * task, which is up-to-date-checked on the wasm, so this executes only when the bundled wasm
 * changes. Not part of the published jar.
 */
public final class GenerateSlangVersion {
    private GenerateSlangVersion() {
    }

    public static void main(String[] args) throws IOException {
        if (args.length != 1) {
            throw new IllegalArgumentException("usage: GenerateSlangVersion <output-resource-dir>");
        }
        Path outputDir = Path.of(args[0]);

        String version;
        try (SlangRuntime runtime = SlangRuntime.load();
                SlangCompiler slang = runtime.forSpirv()) {
            version = slang.version();
        }
        if (version == null || version.isBlank()) {
            throw new IllegalStateException("SlangCompiler.version() returned no build tag.");
        }

        Files.createDirectories(outputDir);
        Files.writeString(
                outputDir.resolve("slang-version.properties"),
                "# Generated by the generateSlangVersion Gradle task from the bundled wasm — do not edit.\n"
                        + "slang.build.tag=" + version + "\n");
        System.out.println("Generated slang-version.properties: " + version);
    }
}
